changelog:
  categories:
     - title: Breaking Changes
       labels:
         - breaking-change
     - title: New Features
       labels:
         - new-features
     - title: Bug fix
       labels:
         - bug-fix
     - title: Dependency updates
       labels:
         - dependency upgrade
     - title: Other Changes
       labels:
         - "*"
